# Generated by Django 5.0.7 on 2024-07-27 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sale_grand_total_sale_sub_total_sale_tax_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='customer',
        ),
    ]
