# Generated by Django 5.0.7 on 2024-08-03 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_sale_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='total_price',
        ),
    ]
